#!/bin/csh
#===== Setup Constants
set NNODEs=1			# Number of Nodes for OMPI
set NCPUs=24			# Number of CPUs for Serpent OMP

#===== Simulation Constants
set noBUsteps = 1		# last burnup step output file
set step = 0			# first suffle step
set stepx = 1 			# last suffle step
set sINP = wh_lfr

#=== Python Constants
#=== SETENV SETS BOTH ENV VARIABLE AND LOCAL VARIABLE BEWARE :(
setenv INPUT fuel.inp
setenv Z_START 1
setenv Z_END 6
setenv FA_START 1
setenv FA_END 48

setenv FRESH_MAT_DATA "92235.09c  2.06136E-04\
92238.09c  2.80617E-02 % natural U\
92234.09c  1.63881E-06\
7014.09c  2.82694E-04\
7015.09c  2.79867E-02 % 99N-15"

setenv MAT_EXTRA_OPTIONS "tmp 923.0  burn 1"
setenv FUEL_VOL "1.0542136E+04"

